import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { config } from '../config/env.js';

let client: SupabaseClient | null = null;

export function getSupabaseClient(): SupabaseClient {
  if (!config.supabaseUrl || !config.supabaseAnonKey) {
    throw new Error('Supabase backend client is not configured');
  }

  if (!client) {
    const rawClient = createClient(config.supabaseUrl, config.supabaseAnonKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    });

    // Wrap getUser to intercept local mock tokens in development / offline environments.
    // Handles two prefixes generated by the frontend mock proxy:
    //   mock-token-<email>           — Email OTP mock path
    //   mock-oauth-token-<provider>  — OAuth mock path (e.g. mock-oauth-token-google)
    const originalGetUser = rawClient.auth.getUser.bind(rawClient.auth);
    rawClient.auth.getUser = async (token?: string) => {
      if (config.enableAuthMock) {
        if (token && token.startsWith('mock-oauth-token-')) {
          const provider = token.substring('mock-oauth-token-'.length);
          return {
            data: {
              user: {
                id: `mock-oauth-uuid-${provider}`,
                email: `${provider}-user@demo.com`,
                app_metadata: { provider },
                user_metadata: {
                  full_name: `Demo ${provider.charAt(0).toUpperCase() + provider.slice(1)} User`,
                },
                aud: 'authenticated',
                created_at: new Date().toISOString(),
              } as any,
            },
            error: null,
          };
        }

        if (token && token.startsWith('mock-token-')) {
          const emailOrPhone = token.substring('mock-token-'.length);
          const digits = emailOrPhone.replace(/\D/g, '');
          return {
            data: {
              user: {
                id: `mock-uuid-${digits || emailOrPhone.replace(/[^a-zA-Z0-9]/g, '')}`,
                phone: digits ? emailOrPhone : '',
                email: emailOrPhone.includes('@') ? emailOrPhone : `${digits}@demo.com`,
                app_metadata: { provider: emailOrPhone.includes('@') ? 'email' : 'phone' },
                user_metadata: {},
                aud: 'authenticated',
                created_at: new Date().toISOString(),
              } as any,
            },
            error: null,
          };
        }
      }

      return originalGetUser(token);
    };

    client = rawClient;
  }

  return client;
}
